In [90]:
import numpy as np
arr1 = np.array([2,89,78])
arr2 = np.array([[2,89,78],[23,56,78],[12,67,89]])
print(arr1)
print(arr2)

[ 2 89 78]
[[ 2 89 78]
 [23 56 78]
 [12 67 89]]


In [91]:
#To find the dimension of the matrix
print(arr1.ndim)
print(arr2.ndim)

1
2


In [92]:
#To find the shape  of the matrix The shape of an array is the number of elements in each dimension.
print(arr1.shape)
print(arr2.shape)

(3,)
(3, 3)


In [93]:
#Get Type
print(arr1.dtype) # it prints 32 in the case of arr1 = np.array([2,89,78],dtype="int32")

int64


In [94]:
print(arr1.itemsize) #Length of one array element in bytes. Since it is in 64bits by default
print(arr2.itemsize)
print(arr1.nbytes) # Total bytes consumed by the elements of the array.
print(arr2.nbytes)

8
8
24
72


In [95]:
#To access a particular element [rowindex,column index] python both indexes start with zero
#[2,89,78],[23,56,78],[12,67,89]]  89->-1 67-> -2 ...  last row -> -1
print(arr2[1,2])
print(arr2[1,0])
print(arr2[-1,0])

78
23
12


In [96]:
#To get specific row
print(arr2[0,:])
print(arr1[-2])
# to get specific column
#[[ 2 89 78] [23 56 78] [12 67 89]]
print(arr2[:,0])
print(arr2[:,1])
# to get specific numbers
arr3 = np.array([[2,89,78,89,123],[23,56,78,99,203],[12,67,89,45,89]])
print(arr2[0,0:3])
print(arr2[0,0:4:2])
print(arr2[0,-1:4:2])
arr2[0,1] = 899
arr2[:,2] = 0
arr2[2,:] = 7
print(arr2)
arr2[2,:] = [11,12,13]
print(arr2)


[ 2 89 78]
89
[ 2 23 12]
[89 56 67]
[ 2 89 78]
[ 2 78]
[78]
[[  2 899   0]
 [ 23  56   0]
 [  7   7   7]]
[[  2 899   0]
 [ 23  56   0]
 [ 11  12  13]]


In [97]:
arr4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr4)
print(arr4[1,1,1])
print(arr4[:,1,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
[[3 4]
 [7 8]]


In [98]:
#Initializing different types of arrays
#All zeros matrix
print(np.zeros(5))
print(np.zeros((2,2))) # Any dimension
#All 1s matrix
print(np.ones(5))
print(np.ones((2,2))) # you can also specify type print(np.ones((2,2),dtype="int32"))
# Any no matrix
print(np.full((2,3),100)) # you can also mention dtype
arr5 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(np.full_like(arr5,8))
print(np.random.rand(2,4)) #random numbers between 0 and 1


[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[100 100 100]
 [100 100 100]]
[[[8 8]
  [8 8]]

 [[8 8]
  [8 8]]]
[[0.59922298 0.40329155 0.32046027 0.48445516]
 [0.94443597 0.61935936 0.55838053 0.52790421]]


In [99]:
print(np.random.randint(5,size=(2,2))) #random integer of your choice 
print(np.random.randint(1,5,size=(2,2))) #random integer of your choice  1 to 5 where 5 is exclusive
print(np.identity(3)) #Identity matrix
arr6 = np.array([[1,2,3]])
print(arr6.repeat(3,axis=1))

[[0 2]
 [1 1]]
[[3 1]
 [2 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 1 1 2 2 2 3 3 3]]


In [100]:
a1 = np.ones((5,5))
a2 = np.zeros((3,3))
a2[1,1] = 9
a1[1:4,1:4] = a2
print(a1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [101]:
#Be careful while copying arrays
a = np.array([1,2,3])
b = a
b[0] = 1001
print(a)
print(b)
#Correct method
a = np.array([1,2,3])
b = a.copy()
b[0] = 1001
print(a)
print(b)

[1001    2    3]
[1001    2    3]
[1 2 3]
[1001    2    3]


In [102]:
#Mathematics
a = np.array([1,2,3])
b = np.array([1,0,1])
print(a+b)
print(a+3)
print(a*3)
print(a-3)
print(a/3)
print(a**2)
print(np.sign(a)) # 1 because of positive integers
print(np.sin(a))

[2 2 4]
[4 5 6]
[3 6 9]
[-2 -1  0]
[0.33333333 0.66666667 1.        ]
[1 4 9]
[1 1 1]
[0.84147098 0.90929743 0.14112001]


In [103]:
#Linear Algebra
a = np.full((2,3),5)
b = np.ones((3,4))
print(a)
print(b)
print(np.matmul(a,b))
#Determinants
c = np.identity(3)
print(np.linalg.det(c))

[[5 5 5]
 [5 5 5]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[15. 15. 15. 15.]
 [15. 15. 15. 15.]]
1.0


In [104]:
#Statistics
stats = np.array([[1,2,0],[99,101,101.5]])
print(np.max(stats))    # rows (axis 0)   cols (axis 1)
print(np.min(stats))
print(np.sum(stats))

101.5
0.0
304.5


In [105]:
#Reorganizing arrays
before = np.array([1, 2, 3, 4, 5, 6])
print(before)
after  = before.reshape((2,3))
print(after)
# Making a random array
gfg = np.array([1, 2, 3, 4, 5, 6])
  
# Required values 12, existing values 6
gfg.resize(3, 4)
print(gfg)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [106]:
#Stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v2,v1]))
print(np.hstack([v1,v2,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]
[1 2 3 4 5 6 7 8 5 6 7 8 1 2 3 4]


In [107]:
file_data = np.genfromtxt('/content/sample_data/array.txt',delimiter=",",dtype="int32")
print(file_data)
file_data>50
print(file_data[file_data>50])
print(np.any(file_data>50,axis=0))
print(np.all(file_data>50,axis=0))
print((file_data>5) & (file_data<100))

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
[196  75 766  75  55 999  78  76  88]
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False False  True False False False False False False False
 False False False False False False]
[[False  True  True  True False  True False False  True  True  True  True
  False False False False False False]
 [False  True  True  True False  True False  True  True False False False
  False  True  True False  True  True]
 [False  True  True  True False  True False False  True False False False
   True  True  True False  True  True]]


In [108]:
a1 = np.array([1,2,3,78,90])
print(a1[[0,1,4]])

[ 1  2 90]
